### PR TITLE
ArmorPlus from CheckCurse to CheckForgeJson

### PR DESCRIPTION
**Pull request by sokratis12GR**

### CODE REVIEW

**Comment by NightKev** [comment]
You forgot the closing '}' for the "forgejson" block.

**Comment by sokratis12GR** [comment]
ForgeJson Updates come with comments right ?

**Comment by NightKev** [comment]
Renol doesn't update any of the mods' comments in NEM as there's not really a reliable way to do so (assuming that's what you mean).

**Comment by sokratis12GR** [comment]
yeah, ok

**Pull request merged**
