### PR TITLE
Added SuperMiner

### PR DESCRIPTION
**Pull request by DuelMonster**

### CODE REVIEW

**Comment by DuelMonster** [comment]
Thank you @Pyker.

**Comment by Pyker** [comment]
Likewise :)

**Comment by DuelMonster** [comment]
Hi @Pyker,

I've noticed that the polling isn't picking up all of my SuperMiner releases since the merge/restart.

It picked up that I had released a new version to MC 1.11.2 last week, but failed to announce the updates for 1.10.2 & 1.11
And again, when I released a new version last night it announced the 1.11.2 update, but failed to announce the 1.11 update.

Could you look into it for me?

Thanks

**Comment by Pyker** [comment]
Hi,

Due to a limitation with our current system, only the most recent file in Curse is processed, so if there are multiple files uploaded in between polling cycles, then it won't see the others.
It's something we've been aware of for a while, and it's being worked on, but finding a good solution is complicated because of how deeply interconnected the entire codebase is.

I hope that clears it up, and I've manually updated the 1.10.2 and 1.11 versions on NEM now.

**Comment by DuelMonster** [comment]
OK, that makes sense, thanks for the explanation.
and thanks for manually updating them for me, I'd have done it myself, just wanted to touch base with you first.  ;)

If I change it to use my Forge version json file, would that solve my issue?

**Comment by Pyker** [comment]
We would need to create an entry for every MC version that we want it to track. That said, I looked at your Forge version JSON file and I'm not sure you're using the correct version format. Instead of `[mc_version]-mod_version` it should just be `mod_version`. If that's corrected then I can make the changes to use that afterwards.

**Comment by DuelMonster** [comment]
Oh, blimey, that seems a little excessive...  Is there no way to avoid the multiple MC version entries?

When I implemented the Forge version JSON file I found that it wouldn't work correctly without the `[mc_version]-`.  This is probably something I've done wrong, but I haven't bothered to look at fixing.
The only thing I have noticed is that as of MC 1.11 the version check only works without the `[mc_version]-`.

**Comment by Pyker** [comment]
For now there's no way to avoid it (it's being worked on as part of that previously mentioned issue). And with that file as it is, it would update the 1.10.2 version to `[1.10.2]-2.1.7.116`, for example.

**Comment by DuelMonster** [comment]
Hmm, ok, well let's leave it as it is for now.
I'll update the versions manually if I need to.

But I will take another look at the Forge versioning and see if I can resolve the issue.  I'll then knock out another pull request.

Thanks for the help.

**Pull request merged**
