### PR TITLE
Added configuration for Chisel

### PR DESCRIPTION
**Pull request by CptSpaceToaster**
I am uncertain if my regex is correct, as it assumes `\d`.  I was able to verify that the pattern worked using: https://regex101.com/

What does `"item": 1` indicate?

### CODE REVIEW

**Comment by CptSpaceToaster** [comment]
Closed, due to an already existing entry for Chisel... I may re-open in the future, to point to Jenkins.

**Comment by Pyker** [comment]
`item` represents the offset of the artifact. The first one is `0`.

**Comment by CptSpaceToaster** [comment]
So if the regex is always going to match 6 entries in the json I specify, I could grab a certain entry using `"item": 0` through `5`?

**Comment by SinZ163** [comment]
the regex will only run on one entry, and that is controlled by `"item" : 0`

**Comment by CptSpaceToaster** [comment]
?

**Comment by Pyker** [comment]
Yes, you can choose the artifact on which the regex will be applied. And the regex will only run on that artifact's filename, like SinZ mentioned.

**Comment by CptSpaceToaster** [comment]
**Ignore if busy**, this is just for my understanding:

So I think I understand the functionaltiy, but I don't get it on a technical level.  Wouldn't you need to **use** the regex to determine all of the possible candidates, and then choose the one you want using `"item"`?  How can you selectively apply regex to a specific artifact if you don't know what artifacts you have to begin with?

They way I understand it, I'm telling the bot to go to this url:
`"url": "http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10/lastSuccessfulBuild/api/json",`

Then it will scan the ENTIRE PAGE using this regex string:
`"regex": "Chisel2-(?P<version>\\d+.\\d+.\\d+).\\d+.jar",`

It will then find a couple "matches", so I tell it which one to use in the sequence:
`"item": 1`
(means, choose the SECOND instance)

right?

If that is the case, then it doesn't sound like I'm choosing which artifact to run regex against, and instead I'm selecting which "match" I want after applying regex to the entire document.

**Comment by Pyker** [comment]
https://github.com/SinZ163/NotEnoughMods/blob/master/NEMP/NEMP_Class.py#L190-L199 is the code that parses Jenkins stuff. We use Jenkins' JSON API for that effect.

**Comment by CptSpaceToaster** [comment]
**Warning, Incorrect Correction:** I apologize in advance
Ya, so you apply regex, gather all of the matches, then use the give "item" number to choose one (if it exists)

This is just a silly correction.  Regex is used to find all of the entries, and then the item number tells the script which one to choose... you don't go out, and magically apply regex to the entry you want...

**Comment by Pyker** [comment]
We only use regex to extract information (such as mod and MC version) from the filenames. We don't use regex on the entire page, we just grab the JSON document and parse it using the JSON decoder.

**Comment by CptSpaceToaster** [comment]
There we go.  Tyvm

**Pull request closed without merging**
